[package]
name = "anilist_cli"
version = "0.1.0"
edition = "2018"

[dependencies]
minreq = { version = "2.4.2", features = ["json-using-serde", "https"] }
serde = { version = "1.0.126", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"